### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by erika-to-omochi** [erika-to-omochi/make_picture_book#59]

**Comment by erika-to-omochi** [comment]
■Webアプリの概要
このサービスは、誰でも手軽に絵本を作成できるプラットフォームです。主に、児童相談所の職員が子どもに心理教育を行う際に活用することを想定しています。このサービスによって、職員の業務負担を軽減し、子どもの理解度を向上させることを目的としています。

■1週間辺りの開発に向けられる時間
- 1週間あたり：40時間

■ProjectsのURL
https://github.com/users/erika-to-omochi/projects/2/views/7

■MVPリリースまで
- [ ] rails new APIモード
- [ ] Fly.ioにデプロイ
- [ ] ReactとNext.jsの環境構築
- [ ] vercelにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] 絵本投稿機能
- [ ] 絵本編集機能
- [ ] 絵本削除機能
- [ ] 絵本へのコメント機能
- [ ] 絵本一覧の閲覧機能
- [ ] マイページ
- [ ] お問い合わせフォーム

■MVP後
- [ ] パスワードリセット機能
- [ ] Google認証
- [ ] 絵本の検索機能・タグ機能
- [ ] Googleアナリティクスの導入
- [ ] ドメインの取得と設定
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] アプリ利用についてのチュートリアル動画
- [ ] OGP画像
- [ ] 絵本の印刷機能
- [ ] 絵本の共有機能
- [ ] 職員向けの心理教育の制度を上げる機能（方法は未確定です）

■MVPレビュー依頼予定日
予定日：2024年 12月22日

■README提出時からの変更点
1. レビュー機能は自前だと実装に時間がかかるため、Googleフォームを利用
2. 卒業が怪しいため、以下の機能をMVPリリースから本リリースに回したいです- Google認証
- パスワードリセット機能
- 絵本の検索機能（タグ機能も）
3. テンプレート機能は難易度が高く、実装が思い浮かばないため、MVP後に後回し

**Comment by kenchasonakai** [comment]
LGTMです！

**Comment by erika-to-omochi** [comment]
ご確認いただき、ありがとうございます😊
